apiVersion: v1
kind: Service
metadata:
  name: ubuntu-service
spec:
  selector:
    app: app-lab
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: 80
  clusterIP: 10.96.0.9
