apiVersion: v1
kind: PersistentVolume
metadata:
  name: blue-pv-cka
spec:
  storageClassName: blue-stc-cka
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: /opt/blue-data-cka
