apiVersion: v1
kind: PersistentVolume
metadata:
  name: fast-pv-cka
spec:
  storageClassName: fast-storage
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Mi
  hostPath:
    path: /tmp/fast-data
