apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-cka
spec:
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
      - mountPath: /var/www/html
        name: nginx-volume
  volumes:
  - name: nginx-volume
    persistentVolumeClaim:
      claimName: nginx-pvc-cka 
  nodeSelector:
    "kubernetes.io/os": linux
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule

#Is the VimSetup exercise just there to ensure that I can never pass the actual exam, per question 21 of the SF-86 no issues @Kim
