apiVersion: apps/v1
kind: Deployment
metadata:
 name: cache-deployment
 labels:
   app: redis
spec:
 replicas: 2
 selector:
   matchLabels:
     app: redis
 template:
   metadata:
     labels:
       app: redis
   spec:
     containers:
     - name: redis
       image: redis:7.0.13
       ports:
       - containerPort: 6379
 strategy:
   type: RollingUpdate
   rollingUpdate:
     maxUnavailable: 30%
     maxSurge: 45%
