apiVersion: v1
kind: Secret
metadata:
  name: secret-basic-auth
type: kubernetes.io/basic-auth
stringData:
  DB_User: REJfVXNlcj1teXVzZXI= # required field for kubernetes.io/basic-auth
  DB_Password: REJfUGFzc3dvcmQbXlwYXNzd29yZA== # required field for kubernetes.io/basic-auth
